# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('descript', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated time')),
            ],
        ),
    ]
