# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20161008_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
