# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=256)),
                ('work_descript', models.TextField()),
                ('condition', models.TextField()),
                ('employment_type', models.IntegerField(choices=[(10, '\u6b63\u793e\u54e1'), (20, '\u5951\u7d04\u793e\u54e1'), (30, '\u30d1\u30fc\u30c8\u30bf\u30a4\u30e0')])),
                ('contact_to', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='member.member')),
            ],
        ),
    ]
