# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated time'),
        ),
    ]
