# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20161004_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
