# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20161030_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='media/upload/recruit/'),
        ),
    ]
