# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField(max_length=2014)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated time')),
            ],
        ),
    ]
