# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('title', models.CharField(max_length=512)),
                ('content', models.CharField(max_length=2014, null=True)),
            ],
        ),
    ]
