# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility', models.IntegerField(choices=[(1, '\u516c\u958b'), (2, '\u4f1a\u54e1\u306e\u307f'), (3, '\u975e\u516c\u958b')])),
                ('rank', models.CharField(choices=[('00', '\u540d\u8a89\u4f1a\u9577'), ('01', '\u4f1a\u9577'), ('02', '\u90e8\u4f1a\u9577'), ('03', '\u5e38\u4efb\u7406\u4e8b'), ('04', '\u76e3\u4e8b')], max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('popular_name', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('biz_type', models.CharField(max_length=256, null=True)),
                ('tel', models.CharField(max_length=128, null=True)),
                ('fax', models.CharField(max_length=128, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=256, null=True)),
                ('url', models.URLField(max_length=256, null=True)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
