# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20161018_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='accessibility',
            field=models.IntegerField(choices=[(1, '\u516c\u958b'), (2, '\u4f1a\u54e1\u306e\u307f'), (3, '\u975e\u516c\u958b')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(choices=[('00', '\u540d\u8a89\u4f1a\u9577'), ('01', '\u4f1a\u9577'), ('02', '\u526f\u4f1a\u9577'), ('10', '\u5e38\u4efb\u7406\u4e8b'), ('11', '\u76e3\u4e8b'), ('12', '\u7406\u4e8b'), ('19', '\u4f1a\u54e1'), ('90', '\u5e38\u4efb\u9867\u554f'), ('91', '\u9867\u554f'), ('92', '\u76f8\u8ac7\u5f79'), ('95', '\u8aee\u554f\u59d4\u54e1'), ('93', '\u53c2\u4e0e')], max_length=2),
        ),
    ]
