# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20161027_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='popular_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
