# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20161107_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='init_entry',
            field=models.BooleanField(default=False),
        ),
    ]
