# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_member_init_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to=b''),
        ),
    ]
