# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20170205_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='home_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='home_fax',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='home_tel',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='home_zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
