# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0014_auto_20170619_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalmember',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('accessibility', models.IntegerField(choices=[(1, '\u516c\u958b'), (2, '\u4f1a\u54e1\u306e\u307f'), (3, '\u975e\u516c\u958b')])),
                ('rank', models.CharField(choices=[('90', '\u5e38\u4efb\u9867\u554f'), ('91', '\u9867\u554f'), ('92', '\u76f8\u8ac7\u5f79'), ('93', '\u53c2\u4e0e'), ('00', '\u540d\u8a89\u4f1a\u9577'), ('01', '\u4f1a\u9577'), ('02', '\u526f\u4f1a\u9577'), ('10', '\u5e38\u4efb\u7406\u4e8b'), ('12', '\u7406\u4e8b'), ('19', '\u4f1a\u54e1'), ('11', '\u76e3\u4e8b'), ('95', '\u8aee\u554f\u59d4\u54e1'), ('99', '\u30b5\u30a4\u30c8\u7ba1\u7406\u8005')], max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('popular_name', models.CharField(blank=True, max_length=128, null=True)),
                ('job_title', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('biz_type', models.CharField(max_length=256, null=True)),
                ('tel', models.CharField(max_length=128, null=True)),
                ('fax', models.CharField(max_length=128, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('init_entry', models.BooleanField(default=False)),
                ('home_zipcode', models.CharField(max_length=8, null=True)),
                ('home_address', models.CharField(max_length=256, null=True)),
                ('home_tel', models.CharField(max_length=128, null=True)),
                ('home_fax', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auth_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'db_table': 'member_history',
                'verbose_name': 'historical member',
                'get_latest_by': 'history_date',
            },
        ),
    ]
