# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_historicalmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmember',
            name='home_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='home_fax',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='home_tel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='home_zipcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_fax',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_tel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_zipcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
