# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-18 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20170626_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='historicalmember',
            name='history_user',
        ),
        migrations.AddField(
            model_name='member',
            name='biz_type_ja',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='biz_type_ko',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='company_name_ja',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='company_name_ko',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name_ja',
            field=models.CharField(max_length=128, null=True, verbose_name='\u304a\u540d\u524d'),
        ),
        migrations.AddField(
            model_name='member',
            name='name_ko',
            field=models.CharField(max_length=128, null=True, verbose_name='\u304a\u540d\u524d'),
        ),
        migrations.DeleteModel(
            name='Historicalmember',
        ),
    ]
