# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=2014, null=True),
        ),
    ]
