# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_auto_20160915_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='locate',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
