# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_auto_20161004_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/task/'),
        ),
    ]
