# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(choices=[('N', '\u97d3\u5546\u30cb\u30e5\u30fc\u30b9'), ('T', '\u7a0e\u7d4c\u30af\u30e9\u30d6'), ('W', '\u9031\u9593\u52d5\u5411')], max_length=1)),
                ('title', models.CharField(max_length=128)),
                ('descript', models.TextField()),
                ('image', models.ImageField(upload_to='upload/news/')),
                ('news_file', models.FileField(upload_to='upload/news/')),
            ],
        ),
    ]
