# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/news/'),
        ),
    ]
