# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160923_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/uploads/news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_file',
            field=models.FileField(upload_to='media/uploads/news/'),
        ),
    ]
