# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20161004_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='stream_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
