# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_stream_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_file',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/news/'),
        ),
    ]
