# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20161031_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='\u516c\u958b\u53ef\u5426'),
        ),
    ]
