# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 03:53
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
