# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='post time'),
        ),
    ]
