# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20170418_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='post time'),
        ),
    ]
